pipeline {
  agent {
    label 'jenkins-agent-node-14'
  }

  stages {
    stage ('Install Dependencies') {
      steps {
        sh """
					cd exchange-cli
					npm install
				"""
      }
    }

    stage ('Build') {
      steps {
        sh """
          cd exchange-cli
          npm run build
        """
      }
    }

    stage ('Unit Tests') {
      steps {
        sh """
          cd exchange-cli
          npm run test:unit
        """
      }
    }

    stage ('Functional Tests') {
      steps {
        sh """
          cd exchange-cli
          npm run test:functional
        """
      }
    }
  }
}